### ISSUE TITLE
Remove duplicated German language

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/form-builder-translations#13]
We have currently two languages: `de` and `de_DE`. We should sort this out on transifex and here:
<img width="279" alt="Screenshot 2021-09-23 at 22 07 51" src="https://user-images.githubusercontent.com/2521888/134584239-6a868997-1f96-4d5b-9ff7-a27590f1a13f.png">

I would personaly leave `de` as `de_DE` is not a valid language code.

**Comment by jnm** [comment]
oh, weird. @tinok, any thoughts about this? it seems that both "German" and "German (Germany)" are listed on transifex: https://www.transifex.com/kobotoolbox/kobotoolbox/

**Comment by tinok** [comment]
I think @JacquelineMorrissette may be able to help. There was a batch import of translated strings at some point. But we should definitely remove one of them. We don't want German (Austria) so the "Germany" part is unnecessary.
